### ISSUE TITLE
Unable to see flux resources in ui when installing the plugin with the helm chart

### ISSUE THREAD

**Issue by ChrisSmiles** [headlamp-k8s/plugins#112]
Im deploying headlamp on EKS using the helm chart which works fine but trying to install the flux plugin with the existing helm  deployment is providing the flux section in the ui. 

<img width="238" alt="image" src="https://github.com/user-attachments/assets/53afc81e-eca2-4b92-a723-0a1ae11ee30e">

```
Helm chart values (using v0.26.0): 
# Default values for headlamp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of desired pods
replicaCount: 1

image:
  # -- Container image registry
  registry: ghcr.io
  # -- Container image name
  repository: headlamp-k8s/headlamp
  # -- Image pull policy. One of Always, Never, IfNotPresent
  pullPolicy: IfNotPresent
  # -- Container image tag, If "" uses appVersion in Chart.yaml
  tag: ""

config:
  # -- base url path at which headlamp should run
  baseURL: ""
  pluginsDir: "/build/plugins"

# -- An optional list of init containers to be run before the main containers.
initContainers:
  - command:
      - /bin/sh
      - -c
      - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
    image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
    imagePullPolicy: Always
    name: headlamp-plugins
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
persistentVolumeClaim:
  enabled: true
  accessModes:
    - ReadWriteOnce
  enabled: true
  size: 1Gi
volumeMounts:
  - mountPath: /build/plugins
    name: headlamp-plugins
volumes:
  - name: headlamp-plugins
    persistentVolumeClaim:
      claimName: headlamp
```
      
```
Logs:
      Defaulted container "headlamp" out of: headlamp, headlamp-plugins (init)
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":339,"time":"2024-11-14T09:58:52Z","message":"Creating Headlamp handler"}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":340,"time":"2024-11-14T09:58:52Z","message":"Kubeconfig path: "}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":341,"time":"2024-11-14T09:58:52Z","message":"Static plugin dir: /headlamp/static-plugins"}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":342,"time":"2024-11-14T09:58:52Z","message":"Plugins dir: /build/plugins"}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":343,"time":"2024-11-14T09:58:52Z","message":"Dynamic clusters support: false"}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":344,"time":"2024-11-14T09:58:52Z","message":"Helm support: false"}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":345,"time":"2024-11-14T09:58:52Z","message":"Proxy URLs: []"}
{"level":"info","pluginPath":"/build/plugins/lost+found/main.js","source":"/headlamp/backend/pkg/plugins/plugins.go","line":197,"error":"stat /build/plugins/lost+found/main.js: permission denied","time":"2024-11-14T09:58:52Z","message":"Not including plugin path, main.js not found"}
{"level":"info","context":"main","clusterURL":"https://172.20.0.1:443","source":"/headlamp/backend/pkg/kubeconfig/kubeconfig.go","line":267,"time":"2024-11-14T09:58:52Z","message":"Proxy setup"}
*** Headlamp Server ***
  API Routers:
{"level":"error","source":"/headlamp/backend/cmd/headlamp.go","line":399,"error":"error loading kubeconfig files: error reading kubeconfig file: open : no such file or directory","time":"2024-11-14T09:58:52Z","message":"loading kubeconfig"}
{"level":"error","source":"/headlamp/backend/cmd/headlamp.go","line":410,"error":"error loading kubeconfig files: error reading kubeconfig file: open /home/headlamp/.config/Headlamp/kubeconfigs/config: no such file or directory","time":"2024-11-14T09:58:52Z","message":"loading dynamic kubeconfig"}

```
After noticing the lost+found error i tried amending the plugin directory arg to pluginsDir: "/build/plugins/flux" but no joy, logs below:
```
{"level":"info","pluginPath":"/build/plugins/flux/main.js","source":"/headlamp/backend/pkg/plugins/plugins.go","line":187,"time":"2024-11-14T10:02:16Z","message":"Not including plugin path, it is not a folder"}
{"level":"info","pluginPath":"/build/plugins/flux/package.json","source":"/headlamp/backend/pkg/plugins/plugins.go","line":187,"time":"2024-11-14T10:02:16Z","message":"Not including plugin path, it is not a folder"}
```
