### ISSUE TITLE
[Flux] Use plugin without access to flux deployed namespace

### ISSUE THREAD

**Issue by sylvainOL** [headlamp-k8s/plugins#161]
Hello,

today Flux plugin mandates that all the users are allowed to list deployments at cluster scope. And in our case, only admins are allowed to do that.

Looking (rapidly) at the code, it seems it's only needed for runtime checks but not for the other pages.

Is there a need I haven't seen?

Otherwise, do you think it could be feasible to remove such constraint?

Thanks!

Sylvain

**Comment by sylvainOL** [comment]
I've continued to dig and also user must be able to get Flux resources (Kustomization, HelmRelease, ...) at cluster level, even if a namespace is given (and same here, our users doesn't have this right)

On the "base" headlamp, different resources are namespace scoped if a namespace is provided

**Comment by sylvainOL** [comment]
Hello @mgalesloot and @ashu8912,

I've tried with version `0.2.0` but it seems that it doesn't work as I expected:

for example, a non privileged user has rights to see helmrelease in specific namespaces but not at cluster level.

This user still does this request tries to get `/clusters/main/apis/helm.toolkit.fluxcd.io/v2/helmreleases HTTP/2`

and this is (obviously) denied:

```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "helmreleases.helm.toolkit.fluxcd.io is forbidden: User \"user@tld\" cannot list resource \"helmreleases\" in API group \"helm.toolkit.fluxcd.io\" at the cluster scope",
  "reason": "Forbidden",
  "details": {
    "group": "helm.toolkit.fluxcd.io",
    "kind": "helmreleases"
  },
  "code": 403
}
```

If I do the "same" request with services, the namespace is well set: `clusters/main/api/v1/namespaces/test/services`

Are you sure it's working as expected?


if it helps, our deployment intent is the following:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    meta.helm.sh/release-name: headlamp
    meta.helm.sh/release-namespace: headlamp
  labels:
    app.kubernetes.io/instance: headlamp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/version: 0.30.0
    helm.sh/chart: headlamp-0.30.1
    helm.toolkit.fluxcd.io/name: headlamp
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: headlamp
  namespace: headlamp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: headlamp
      app.kubernetes.io/name: headlamp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: headlamp
        app.kubernetes.io/name: headlamp
    spec:
      containers:
      - args:
        - -in-cluster
        - -plugins-dir=/build/plugins
        image: ghcr.io/headlamp-k8s/headlamp:v0.30.0
        imagePullPolicy: Always
        name: headlamp
        ports:
        - containerPort: 4466
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            ephemeral-storage: 200Mi
            memory: 128Mi
          requests:
            cpu: 50m
            ephemeral-storage: 200Mi
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsGroup: 101
          runAsNonRoot: true
          runAsUser: 100
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /build/plugins
          name: headlamp-plugins
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - /bin/sh
        - -c
        - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:v0.2.0@sha256:6727bb58c95feef9f62f8fe125c244601d31ca62eab546b0f88c045560ed33de
        imagePullPolicy: Always
        name: headlamp-plugins
        resources:
          limits:
            ephemeral-storage: 100Mi
            memory: 128Mi
          requests:
            cpu: 50m
            ephemeral-storage: 100Mi
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 101
          runAsNonRoot: true
          runAsUser: 100
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /build/plugins
          name: headlamp-plugins
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 100
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: headlamp
      serviceAccountName: headlamp
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          sizeLimit: 100Mi
        name: headlamp-plugins
```
