### ISSUE TITLE
Flux: Inventory of an Kustomization - only standard Kubernetes objects are listed

### ISSUE THREAD

**Issue by daniel-ciaglia** [headlamp-k8s/plugins#162]
Hi there,

as the title says, only standard Kubernetes objetcs are shown in the inventory of a given Flux Kustomization. I believe this behaviour comes from here:
- https://github.com/headlamp-k8s/plugins/blob/c9039fbc9bf05f9d9cc9bf6e34903e83852a3fe4/flux/src/inventory/index.tsx#L35
- https://github.com/headlamp-k8s/plugins/blob/c9039fbc9bf05f9d9cc9bf6e34903e83852a3fe4/flux/src/inventory/index.tsx#L1 
- https://github.com/headlamp-k8s/headlamp/tree/main/frontend/src/lib/k8s

Find attached a screenshot and YAML snippet to illustrate this.

![Image](https://github.com/user-attachments/assets/1ce54a4f-1fc2-4aef-825b-8148a3482c94)

```YAML
status:
  inventory:
    entries:
      - id: flux-system_lib-eventing_infra.contrib.fluxcd.io_Terraform
        v: v1alpha2
      - id: flux-system_lib-eventing-iac_source.toolkit.fluxcd.io_OCIRepository
        v: v1beta2
```
