### ISSUE TITLE
Flux: HelmRelease sourceRef from different namespace causes 404

### ISSUE THREAD

**Issue by viceice** [headlamp-k8s/plugins#177]
It seems the Flux plugin can't handle source refs of HelmRepository when it's located in a different namespace:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami-charts
  namespace: flux-system # needed for renovate
spec:
  type: oci
  url: oci://ghcr.io/visualon/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opensearch
  namespace: services
spec:
  interval: 30m
  timeout: 30m
  chart:
    spec:
      chart: opensearch
      version: 1.6.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 12h
```

Errors:

![Image](https://github.com/user-attachments/assets/d8952863-ea8c-492a-921b-195dc6784002)
