### ISSUE TITLE
Flux: v0.2.0 can't create plugins/flux directory

### ISSUE THREAD

**Issue by joryirving** [headlamp-k8s/plugins#214]
Trying to update my flux plugin from v0.1.0-beta-2, and my init container is throwing errors stating it can't overwrite the .json files already existing.

I tried to add a command to delete them first, but got a permission denied, so I just blew away the PVC to start from scratch, and now I'm getting
`cp: can't create directory '/build/plugins/flux': Permission denied ` 

This is my updated non-working hr:
https://github.com/joryirving/home-ops/blob/8ea0eaf26d14816aad14266af941f7e4f8855198/kubernetes/apps/base/flux-system/headlamp/helmrelease.yaml

This is my reverted, working hr on the old version:
https://github.com/joryirving/home-ops/blob/ff723a4a7d3ddce3ab7723c8e0d545f9bab24fb5/kubernetes/apps/base/flux-system/headlamp/helmrelease.yaml

I can't find anything in the changelog where I need to do anything other than just bump the version.

**Comment by Smana** [comment]
I got exactly the same issue, thanks for the tip @joryirving . I also downgraded the version in [my repo](https://github.com/Smana/cloud-native-ref).

**Comment by mattaurus** [comment]
I always use emptyDir, the size of the plugin artefacts is quite small.

**Comment by joryirving** [comment]
Since I use volsync to backup/restore my PVCs, I found it was related to the securityContext.

Adding this to my helmchart fixed it:

```
    securityContext:
      runAsNonRoot: true
      privileged: false
      runAsUser: 1000
      runAsGroup: 100
```

**Comment by geanttechnology** [comment]
Here is the reason why you cannot create a directory under (/): It can only be modified by the root user and the entrypoint is using headlamp user

![Image](https://github.com/user-attachments/assets/7e2ef44f-455f-420f-aa82-5f1c1dbaf1d1)

**Comment by geanttechnology** [comment]
Here is how to configure the new flux headlamp-plugin-flux:v0.2.0 to work properly:

``` initContainers:
      - command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:v0.2.0 
        imagePullPolicy: Always
        name: headlamp-plugins
        securityContext:
          runAsNonRoot: false
          privileged: false
          runAsUser: 0
          runAsGroup: 101```

**Comment by kksudo** [comment]
Added the correct instructions to the README of the flux plugin
https://github.com/kksudo/plugins/tree/bugfix/fix-multiarch/flux

```yaml
config:
      pluginsDir: /build/plugins
    initContainers:
      - command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/ && chown -R 100:101 /build
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        imagePullPolicy: Always
        name: headlamp-plugins
        securityContext:
          runAsNonRoot: false
          privileged: false
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    persistentVolumeClaim:
      accessModes:
        - ReadWriteOnce
      enabled: true
      size: 1Gi
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    volumes:
      - name: headlamp-plugins
        persistentVolumeClaim:
          claimName: headlamp # The name of the Helm release
```
