### ISSUE TITLE
Prometheus Plug-In: Also detect victoriametrics

### ISSUE THREAD

**Issue by micw** [headlamp-k8s/plugins#37]
Hello,

I run victoriametrics in my stacks (as replacement of prometheus). It should provide the same information (at least with lens it does) but it's not detected by the plug-in.

Could detection of victoriametrics be added? What is the exact mechanism to check if prometheus is available in the cluster or not?

**Comment by joaquimrocha** [comment]
@yolossn Can you check this one?

**Comment by yolossn** [comment]
The plugin searches the cluster for pods with the `app.kubernetes.io/name=prometheus` label to identify the prometheus pod to query the metrics. can you check if your prometheus pod has this label?

> kubectl get pods -l app.kubernetes.io/name=prometheus --all-namespace

We are working on making the prometheus url configurable so that the user can configure the prometheus endpoint to fetch the metrics from.

**Comment by avanier** [comment]
Just chiming in to say I've had a look into this, and it's not possible to overwrite that annotation if you're deploying VictoriaMetrics through the the VM operator _(which is currently the recommended way to deploy this)_.

I'm assuming it's mostly a question of extending [this code](https://github.com/headlamp-k8s/plugins/blob/main/prometheus/src/request.tsx#L7) to support the relevant VictoriaMetrics targets such as `vmsingle` and `vmselect`.

**Comment by vaskozl** [comment]
The new settings panel does allow configuring the endpoint to e.g. `victoria-metrics/vmsingle-stack:8429` but it needs to be configured per client as the settings are local when running in-cluster. There is also a chance they get cleared.

It would be better for users if this could be set with an env var or similar. As I result I have opted to use a auxiliary svc that creates the expected labels.

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: prometheus
  name: prom-adapter
  namespace: victoria-metrics
spec:
  ports:
  - name: http
    port: 8429
    protocol: TCP
    targetPort: 8429
  selector:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: vmsingle
  type: ClusterIP
```
